"""Constants for the NeoRé integration."""

from __future__ import annotations

DOMAIN = "neore"

DEFAULT_USERNAME = "foxtrot"
DEFAULT_PASSWORD = "foxtrotAP1"
DEFAULT_SCAN_INTERVAL = 15

CONF_BASE_URL = "base_url"

# Read-only temperatures.
OBJECT_OUTDOOR_TEMPERATURE = "tvenek"
OBJECT_RETURN_TEMPERATURE = "tvrat"
OBJECT_ROOM_TEMPERATURE = "tobj"
OBJECT_FLOW_TEMPERATURE = "InTtopv"
OBJECT_DHW_TEMPERATURE = "InTtuv"
OBJECT_ROOM_INPUT_TEMPERATURE = "InTobj"
OBJECT_POOL_TEMPERATURE = "InTbaz"

# Writable temperatures / set-points.
OBJECT_DHW_SETPOINT = "ttuvreqmain"
OBJECT_ROOM_SETPOINT = "tobjekreq"
OBJECT_WATER_CORRECTION = "korekce"
OBJECT_COOLING_WATER_SETPOINT = "tempcoolw"
OBJECT_POOL_WATER_TEMPERATURE = "tbazenwat"
OBJECT_POOL_SETPOINT = "tbazenreq"
OBJECT_HEATING_CURVE = "NeoEkvValue"
HEATING_CURVE_FIELDS: tuple[str, ...] = (
    "TempEkvA",
    "TempEkvB",
    "TempEkvC",
    "TempEkvD",
)

# Performance.
OBJECT_FLOW_RATE = "ActFlow"
OBJECT_HEATING_POWER = "ActHeaPow"
OBJECT_HEAT_ENERGY = "HeatSumCnt"
OBJECT_CIRCULATION_PUMP_REQUESTED_POWER = "OuPWM1"
OBJECT_HEAT_PUMP_REQUESTED_POWER = "pow1st"

# Other state and controls.
OBJECT_TARIFF_PERMISSION = "sazba"
OBJECT_MAIN_ENABLE = "chodhlavni"
OBJECT_DHW_ENABLE = "tuvmainon"
OBJECT_HEATING_MODE = "heating_int"
OBJECT_ERROR_BLOCK = "errorblock"
OBJECT_ERROR_CODE = "errcode"
OBJECT_POOL_DEFINITION = "BazDef"
OBJECT_POOL_ENABLE = "bazenmainon"
OBJECT_POOL_HEATING = "bazenon"

# Optional metadata published by NeoApi v2.
OBJECT_NEORE_INFO = "IniNeoRe"
OBJECT_SIMPLY_NEO_VERSION = "SimplyNeoVer"
OBJECT_PLC_PROGRAM_INFO = "PLCPrgInfo"
OBJECT_PLC_INFO = "PLCInfo"

DATA_MODEL = "_model"
DATA_API_VERSION = "_api_version"
DATA_SW_VERSION = "_sw_version"
DATA_PROGRAM_NAME = "_program_name"
DATA_PROGRAM_COMPILED = "_program_compiled"
DATA_PROGRAM_STAMP = "_program_stamp"
DATA_PLC_FAMILY = "_plc_family"
DATA_PLC_TYPE = "_plc_type"
DATA_PLC_SPECIFICATION = "_plc_specification"
DATA_HW_VERSION = "_hw_version"
DATA_SERIAL_NUMBER = "_serial_number"

BOOLEAN_OBJECTS: frozenset[str] = frozenset(
    {
        OBJECT_TARIFF_PERMISSION,
        OBJECT_MAIN_ENABLE,
        OBJECT_DHW_ENABLE,
        OBJECT_HEATING_MODE,
        OBJECT_ERROR_BLOCK,
        OBJECT_POOL_DEFINITION,
        OBJECT_POOL_ENABLE,
        OBJECT_POOL_HEATING,
    }
)

# Root objects the integration knows how to consume continuously. NeoEkvValue
# is read as one structure and then flattened into four writable HA numbers.
POLL_OBJECTS: tuple[str, ...] = (
    OBJECT_OUTDOOR_TEMPERATURE,
    OBJECT_RETURN_TEMPERATURE,
    OBJECT_ROOM_TEMPERATURE,
    OBJECT_FLOW_TEMPERATURE,
    OBJECT_DHW_TEMPERATURE,
    OBJECT_ROOM_INPUT_TEMPERATURE,
    OBJECT_POOL_TEMPERATURE,
    OBJECT_DHW_SETPOINT,
    OBJECT_ROOM_SETPOINT,
    OBJECT_WATER_CORRECTION,
    OBJECT_COOLING_WATER_SETPOINT,
    OBJECT_POOL_WATER_TEMPERATURE,
    OBJECT_POOL_SETPOINT,
    OBJECT_HEATING_CURVE,
    OBJECT_FLOW_RATE,
    OBJECT_HEATING_POWER,
    OBJECT_HEAT_ENERGY,
    OBJECT_CIRCULATION_PUMP_REQUESTED_POWER,
    OBJECT_HEAT_PUMP_REQUESTED_POWER,
    OBJECT_TARIFF_PERMISSION,
    OBJECT_MAIN_ENABLE,
    OBJECT_DHW_ENABLE,
    OBJECT_HEATING_MODE,
    OBJECT_ERROR_BLOCK,
    OBJECT_ERROR_CODE,
    OBJECT_POOL_DEFINITION,
    OBJECT_POOL_ENABLE,
    OBJECT_POOL_HEATING,
)

SUPPORTED_ROOT_OBJECTS: frozenset[str] = frozenset(
    (
        *POLL_OBJECTS,
        OBJECT_NEORE_INFO,
        OBJECT_SIMPLY_NEO_VERSION,
        OBJECT_PLC_PROGRAM_INFO,
        OBJECT_PLC_INFO,
    )
)
